### ISSUE TITLE
onedrive CSP

### ISSUE THREAD

**Issue by jeromebt** [helmlingp/WS1UEM_Profiles#1]
Hi Phil, this doesn't seems to work. 

Thanks Jerome
<Replace>
	<CmdID>2</CmdID>
	<Item>		
        <Target><LocURI>./Device/Vendor/MSFT/Policy/Config/OneDriveNGSC~Policy~OneDriveNGSC/KFMOptInNoWizard</LocURI></Target>
		<Data><![CDATA[<enabled/> <data id="KFMOptInNoWizard_TextBox" value="1111-2222-3333-4444-5555"/> <data 
        id="KFMOptInNoWizard_Dropdown" value="0"/>]]></Data>
	</Item>
</Replace>

**Comment by helmlingp** [comment]
fixed. Added `<data id="KFMOptInNoWizard_Desktop_Checkbox" value="true"/><data id="KFMOptInNoWizard_Documents_Checkbox" value="true"/><data id="KFMOptInNoWizard_Pictures_Checkbox" value="true"/>` as these new policy options are required
